services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host
    depends_on:
      - server

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/AppDB
      - NODE_ENV=development
    volumes:
      - ./Server:/app
      - /app/node_modules
    command: npx nodemon -L src/app.mjs
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
